version: "3.9"
services:
  coqui-tts:
    build: .
    ports:
      - "5005:5002"   # Coolify maps 5005 on host -> 5002 in container
    # Run uvicorn programmatically to avoid the CLI arg conflict
    entrypoint:
      - python3
      - -c
      - |
        import os, uvicorn
        from TTS.server.server import app
        uvicorn.run(app,
                    host="0.0.0.0",
                    port=int(os.environ.get("PORT", "5002")),
                    log_level="info")
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:5002/docs"]
      interval: 10s
      timeout: 3s
      retries: 10
    environment:
      - PORT=5002




