services:
  coqui-tts:
    build: .
    ports:
      - "5005:5002"
    command: ["python3","-m","TTS.server.server","--port","5002"]
    healthcheck:
      # `/docs` is FastAPI-only, don’t use it
      test: ["CMD-SHELL","curl -s -f http://localhost:5002/ >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10







